package com.opd.opd.entity.enums;

public enum ClinicType {
    EYE,ENT,DENTAL,GENERAL,PHYSIOTHERAPY,PSYCHIATRIST,DERMATOLOGIST,PEDIATRICIAN,ORTHOPEDICIAN,GYNECOLOGIST,UROLOGIST,CARDIOLOGIST,NEUROLOGIST,GASTROENTEROLOGIST,ENDOCRINOLOGIST,RADIOLOGIST,ONCOLOGIST,NEPHROLOGIST,RHEUMATOLOGIST,ALLERGIST,IMMUNOLOGIST,PULMONOLOGIST,HEMATOLOGIST,INFECTIOUS_DISEASE_SPECIALIST,EMERGENCY_MEDICINE_SPECIALIST
}
